apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadummyproject-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: dummyproject
  template:
    metadata:
      labels:
        app: dummyproject
    spec:
      containers:
      - name: dummyproject
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
