apiVersion: v1
kind: Service
metadata:
  name: javadummyproject-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: dummyproject
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
